### ISSUE TITLE
Equals sign from the query filter is dropped

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade.science#13]
How to reproduce:

Try rather complex query e.g. `elements HAS ANY "C","Si","Ge","Sn","Pb" AND nelements=2`: https://optimade.science/?filter=elements%20HAS%20ANY%20"C","Si","Ge","Sn","Pb"%20AND%20nelements=2&providers=threedd while only one provider is enabled.

Then enable arbitrary other new one, clicking by its avatar. The query in the input box changes on its own.

The problem is in the `=` sign in this part of the query: `nelements=2`

**Comment by blokhin** [comment]
@PaulMaly ping

**Comment by PaulMaly** [comment]
Yea seems it's a router bug. Could you please submit an issue to [svelte-pathfinder](https://github.com/PaulMaly/svelte-pathfinder) repo?

**Comment by PaulMaly** [comment]
Fixed with #19

**Comment by blokhin** [comment]
Now fixed in production, thanks!
