### ISSUE TITLE
Individual entry preview generates incorrect URLs

### ISSUE THREAD

**Issue by merkys** [tilde-lab/optimade.science#2]
I tried accessing data in the COD from the search results (https://optimade.science/#filter=elements%20HAS%20%22Ca%22), but the following URL of an individual entry is not supported in the COD:

https://www.crystallography.net/cod/optimade/structures/?filter=id=1000007

Note the `/` before `?`, should be `structures?filter=id=1000007` (without `/` before `?`). I believe the following line is responsible:

https://github.com/tilde-lab/optimade.science/blob/be60495f4b7ecd09b28270fca8f246759c19c821/index.html#L502

**Comment by blokhin** [comment]
@merkys do you know, if this is the case for the COD only or for the other databases as well?

By experience, trailing slash in the URLs may indeed lead to the problems.

**Comment by merkys** [comment]
@blokhin Trailing slashes are not explicitly mentioned in OPTIMADE specification, but from most of the examples it seems that they are not used:
> Examples of valid entry listing endpoint URLs:
>
> - http://example.com/optimade/v1/structures
> - http://example.com/optimade/v1/calculations

Examples given in the specification:
> /structures?filter=nelements=2
> /structures?filter=a=1 AND b=2
> http://example.com/optimade/v1/structures?page_limit=100

There is, though, a single observation of `/?`, but I guess this is unintended. I will open an issue to clarify.

**Comment by blokhin** [comment]
Hopefully fixed now 😊
