### ISSUE TITLE
make link to optimade standard more visible

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/optimade.science#20]
Just copying this from an earlier email to evgeny:

I was going to suggest to add a link to the optimade standard (so that people can understand what to put in the search fied) - then I realized that there was already a link at the bottom of the page.
   It might make sense to move the footer (or at least the link to the standard) up to where the content of the page ends - I guess many people will be like me and overlook it at the very bottom of the page. I attach a screenshot just to illustrate the dimensions on my screen.
   Or one could add a link to either directly to the "filter=" or on a Questionmark icon close to there that directly links to the optimade filter language specification

![image](https://user-images.githubusercontent.com/1053245/109645718-834a7c00-7b57-11eb-85bf-e32fb2619c7b.png)

**Comment by ltalirz** [comment]
It would probably also make sense to use instead of "Start typing..." an example query that is known to produce an interesting result

**Comment by blokhin** [comment]
Done.
