### ISSUE TITLE
Wrong version for most providers

### ISSUE THREAD

**Issue by shyamd** [tilde-lab/optimade.science#4]
It looks like this is primarily pinging the `v0` endpoint, whereas most implementations have settled on the first implementation being `v1`. That's causing the app to not find any sources other than `pcod` or `tcod`.

**Comment by blokhin** [comment]
@shyamd we're now rewriting the app completely, the update will be (hopefully) rolled out in a couple of weeks 👍

**Comment by blokhin** [comment]
Hopefully fixed now 😊
