### ISSUE TITLE
Use project logos for the avatars

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade.science#46]
To increase the loading speed, I'd propose generating a single sprite for all the logos, similar to https://mpds.io/aets.jpg vs. https://mpds.io/#polyhedra

@Valexr what do you think?

**Comment by Valexr** [comment]
> To increase the loading speed, I'd propose generating a single sprite for all the logos, similar to https://mpds.io/aets.jpg vs. https://mpds.io/#polyhedra

I think it doesn't affect the download speed.

**Comment by Valexr** [comment]
> > To increase the loading speed, I'd propose generating a single sprite for all the logos, similar to https://mpds.io/aets.jpg vs. https://mpds.io/#polyhedra

What logos are you talking about?

**Comment by Valexr** [comment]
https://github.com/tilde-lab/optimade.science/pull/47
