### ISSUE TITLE
Pagination requests `page_number=0` which is unsupported

### ISSUE THREAD

**Issue by ml-evs** [tilde-lab/optimade.science#54]
When trying to query e.g. odbx, all filters return an error about `page_number=0` being requested. OPTIMADE standardizes 3 different pagination types, number-based, offset-based an cursor-based. `page_number=0` is invalid as number-based pagination starts at 1. Most databases actually use offset-based pagination, perhaps this should be used here instead?

IMO we should standardize an error code/message in the specification for unsupported pagination types, as it is not clear how to negotiate with a provider to figure this out...

**Comment by blokhin** [comment]
closing as per our discussion
