### ISSUE TITLE
Algo for avatar abbreviations should be improved

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade.science#8]
See `Avatar` component https://github.com/tilde-lab/optimade.science/tree/master/src/components/Avatar

**Comment by hodovani** [comment]
@blokhin sorry, could you please specify what should be improved in the algorithm for avatar abbreviations.

**Comment by hodovani** [comment]
It would be hard to put full id in an avatar.

![image](https://user-images.githubusercontent.com/12833067/105396133-36a28580-5c28-11eb-9407-42270ae65ffe.png)

Even if we make circles bigger

![image](https://user-images.githubusercontent.com/12833067/105399080-cc8bdf80-5c2b-11eb-86d6-e920a0fd69d1.png)

We might need to decrease a font-size

![image](https://user-images.githubusercontent.com/12833067/105399155-ec230800-5c2b-11eb-80ba-633ed9e77cfb.png)

@blokhin what do you think would be the best solution?

**Comment by hodovani** [comment]
We don't receive a version of a provider at the moment. 

![image](https://user-images.githubusercontent.com/12833067/105399572-79665c80-5c2c-11eb-9bdd-a5bfe5ee1fdb.png)

Where can we find it?

**Comment by blokhin** [comment]
Done in production.
