### ISSUE TITLE
Popup-stopper for IE<=11 and all the smartphones

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/optimade.science#9]
Unfortunately, a [current one](https://github.com/tilde-lab/optimade.science/blob/b3bf6d62eb8b4257f5812f84426beb5296a9dcc1/src/index.html#L17) doesn’t work for IE.

**Comment by hodovani** [comment]
I think we should use some javascript code to make it works. I'll check it after I found out how to run IE on Mac.

**Comment by blokhin** [comment]
To replace 1024px in the media query with the mobile breakpoint:
```
.zoom-image {
	position: relative;
}

.zoom-image::before {
	content: "";
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	background: transparent;
}

@media only screen and (min-width: 1024px) {
	.zoom-image::before {
		display: none;
	}
}```
